version: '3'
services:
  elasticsearch_demo:
    build:
      context: ../elasticsearch_demo
    command: rails s -b 0.0.0.0 -p 3000
    volumes:
      - ../elasticsearch_demo:/app
    ports:
      - "3000:3000"